### ISSUE TITLE
Add RMSE

### ISSUE THREAD

**Issue by robmarkcole** [andfanilo/regression-streamlit-viz#1]
would be nice to compute the RMSE or similar :-)

**Comment by andfanilo** [comment]
It's something I did in the previous version, I'll port it shortly ;)

**Comment by andfanilo** [comment]
Ok this should do.

Also leveraged tvst's SessionState gist to store the minimum RMSE you obtained manually. You can check on master branch :)

![image](https://raw.githubusercontent.com/andfanilo/regression-streamlit-viz/72208e2/demo.png)
